# Generated by Django 2.0.5 on 2018-07-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_number',
            field=models.IntegerField(null=True),
        ),
    ]
