# Generated by Django 2.0.5 on 2018-07-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180711_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_pic',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
