# Generated by Django 2.0.7 on 2018-07-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
