# Generated by Django 2.1 on 2018-08-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('speciality', models.TextField(max_length=200)),
                ('mobile_number', models.IntegerField(null=True)),
                ('email_address', models.CharField(max_length=100)),
                ('lawyer_pic', models.ImageField(blank=True, upload_to='lawyer_img')),
            ],
        ),
    ]
